name: Deploy Assignment1 DevOps

on:
  push:
    branches:
      - main
      - dev
      - prod
      - fix
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync config file to S3 based on branch
      run: |
        BUCKET_NAME="techeazy-devops-config"
        if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
          aws s3 cp assignment1/config/dev.json s3://$BUCKET_NAME/dev.json
        elif [ "${{ github.ref }}" == "refs/heads/prod" ]; then
          aws s3 cp assignment1/config/prod.json s3://$BUCKET_NAME/prod.json
        elif [ "${{ github.ref }}" == "refs/heads/fix" ]; then
          aws s3 cp assignment1/config/fix.json s3://$BUCKET_NAME/fix.json
        else
          echo "Branch not recognized for config upload"
        fi

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          set -e
          REPO_URL="https://github.com/Trainings-TechEazy/test-repo-for-devops.git"
          BRANCH="main"
          APP_JAR_NAME="hellomvc-0.0.1-SNAPSHOT.jar"

          # Kill existing app if running
          echo "Checking for existing app processes..."
          if pgrep -f "java.*$APP_JAR_NAME"; then
            echo "Found old app processes. Killing..."
            sudo pkill -f "java.*$APP_JAR_NAME"
            sleep 5 # Wait for process termination
            echo "Old app processes killed."
          else
            echo "No existing app running."
          fi

          if [ -d /home/ubuntu/techeazy-devops ]; then
            cd /home/ubuntu/techeazy-devops
            git remote set-url origin $REPO_URL
            git fetch origin
            git reset --hard origin/$BRANCH
          else
            git clone --branch $BRANCH $REPO_URL /home/ubuntu/techeazy-devops
            cd /home/ubuntu/techeazy-devops
          fi

          mvn clean package

          # Start the app fully detached from the SSH session
          sudo setsid nohup java -jar target/$APP_JAR_NAME --server.port=80 > app.log 2>&1 < /dev/null &
          sleep 25  # Increased sleep time for app startup

          # Check the root endpoint
          if ! curl -f http://localhost:80/hello; then
            echo "App failed to start or is not reachable"
            sudo tail -n 50 app.log
            exit 1
          fi